export const asyncRouter = {
	"msg": "操作成功",
	"code": 200,
	"data": [
		{
			"name": "Business",
			"path": "/business",
			"hidden": false,
			"redirect": "noRedirect",
			"component": "Layout",
			"alwaysShow": false,
			"meta": { "title": "交易订单", "icon": "business", "noCache": false, "parentTitle": "交易管理" },
			"children": [
				{
					"name": "OrderList",
					"path": "list",
					"hidden": false,
					"component": "BusinessManage/order-list",
					"meta": { "title": "订单列表", "icon": "", "noCache": false, "parentTitle": "" },
				},
				{
					"name": "OrderChange",
					"path": "change",
					"hidden": false,
					"component": "BusinessManage/order-change",
					"meta": { "title": "交易变更", "icon": "", "noCache": false, "parentTitle": "" },
				},
				{
					"name": "OrderTracking",
					"path": "tracking",
					"hidden": false,
					"component": "BusinessManage/order-tracking",
					"meta": { "title": "订单跟踪", "icon": "", "noCache": false, "parentTitle": "" },
				},
			],
		},
		{
			"name": "Settlement",
			"path": "/settlement",
			"hidden": false,
			"redirect": "index",
			"component": "Layout",
			"meta": { "title": "订单结算", "icon": "settlement", "noCache": false, "parentTitle": "结算功能" },
			"children": [
				{
					"name": "Basics",
					"path": "basics",
					"hidden": false,
					"component": "Settlement/Basics",
					"meta": { "title": "划款表", "icon": "", "noCache": false, "parentTitle": "" },
				},
				{
					"name": "Bond",
					"path": "bond",
					"hidden": false,
					"component": "Settlement/Bond",
					"meta": { "title": "保证金划款表", "icon": "", "noCache": false, "parentTitle": "" },
				},
				{
					"name": "EarnestMoney",
					"path": "earnest",
					"hidden": false,
					"component": "Settlement/earnestMoney",
					"meta": { "title": "补划订单", "icon": "", "noCache": false, "parentTitle": "" },
				},
				{
					"name": "UnbalancedAccount",
					"path": "unbalanced",
					"hidden": false,
					"component": "Settlement/unbalancedAccount",
					"meta": { "title": "未结算统计", "icon": "", "noCache": false, "parentTitle": "" },
				},
			],
		},
		{
			"name": "Serve",
			"path": "/serve",
			"hidden": false,
			"redirect": "noRedirect",
			"component": "Layout",
			"alwaysShow": true,
			"meta": { "title": "客户服务", "icon": "serve", "noCache": false, "parentTitle": "平台服务" },
			"children": [
				{
					"name": "Logistics",
					"path": "logistics",
					"hidden": false,
					"component": "Serve/logistics",
					"meta": { "title": "物流管理", "icon": "", "noCache": false, "parentTitle": "" },
				},
			],
		},
		{
			"name": "Passageway",
			"path": "/passageway",
			"hidden": false,
			"redirect": "index",
			"component": "Layout",
			"meta": { "title": "用户管理", "icon": "passageway", "noCache": false, "parentTitle": "个人中心" },
			"children": [
				{
					"name": "Configure",
					"path": "configure",
					"hidden": false,
					"component": "Passageway/configure",
					"meta": { "title": "个人信息", "icon": "", "noCache": false, "parentTitle": "" },
				},
				{
					"name": "Cashier",
					"path": "cashier",
					"hidden": false,
					"component": "Passageway/cashier",
					"meta": { "title": "支付网址", "icon": "", "noCache": false, "parentTitle": "" },
				},
				{
					"path": "account",
					"name": "Account",
					"hidden": false,
					"component": "Passageway/account",
					"meta": { "title": "账户管理", "icon": "", "noCache": false, "parentTitle": "" },
				},
			],
		},
		{
			"name": "Other",
			"path": "/other",
			"hidden": false,
			"redirect": "index",
			"component": "Layout",
			"alwaysShow": true,
			"meta": { "title": "基础设置", "icon": "other", "noCache": false, "parentTitle": "其他" },
			"children": [
				{
					"name": "DownloadApi",
					"path": "downloadapi",
					"hidden": false,
					"component": "Other/downloadApi",
					"meta": { "title": "接口下载", "icon": "", "noCache": false, "parentTitle": "" },
				},
			],
		},
	],
};